### ISSUE TITLE
SBD reflecting 0.00 in my pending payout

### ISSUE THREAD

**Issue by cckole** [samvanemelen/debato#10]
### Description

I just noticed that my pending SBD isn't displayed in the wallet. I'm having 3.281SBD and 9.650Steem but on the debato Steem wallet, I can't see the SBD recorded. It reads 0.00 SBD as my pending reward.

###Expected behavior

I expected to see both my pending SBD and Steem reward in the wallet.

### Steps to reproduce

- Log in to debato.org with your Steem username and password

- Click on the menu button by the top left side

- Click on profile at the bottom

- Cluck on wallet

- Check the value you have in your SBD pending payout down below the wallet. Make sure to check the value you have in your steemit wallet to compare.

### Reproducing the bug

Below are the steem and debato wallet images showing the different pending payout. Focus on SBD

![Screenshot_20190501-111303](https://user-images.githubusercontent.com/36272218/57013203-5008d000-6c02-11e9-91ac-16c31d80b42b.png)

![Screenshot_20190501-102559](https://user-images.githubusercontent.com/36272218/57012989-11bee100-6c01-11e9-9645-6dce5323c36d.png)

### Device used

Techno spark K7
Operating system: Android 7.0

Browser used: Chrome

**Comment by samvanemelen** [comment]
Thank you for pointing it out! the SBD value was retrieved from the wrong parameter, but this should be fixed now.
