### ISSUE TITLE
Couldn't start a discussion 

### ISSUE THREAD

**Issue by cckole** [samvanemelen/debato#11]
### Project info
Name: Debato

### Description

After filling all the spaces to start a discussion, I clicked on publish but my discussion wasn't published. There was no response from the click.

### Expected behavior

After writing my discussion and filling the tag and other stuffs, I expected my discussion to be published to the block chain when I clicked on publish.

### Steps to reproduce

After login into debato with your Steem username and key

- Click on the menu button by the top left side
- Click on start discussion
- Fill all the boxes by writing the brief discussion, elaborate your statement, fill in an image URL and tag
- Click on publish and see the reaction.

### Reproducing the behaviour

https://youtu.be/B18FOChHb80

Device used
Techno K7 Android 7.0 & PC

Browser: Chrome.

I would love this issue to be fixed asap.

Thanks.

**Comment by samvanemelen** [comment]
This is indeed detrimental for using debato. I'll get to it as fast as possible.

**Comment by cckole** [comment]
Alright. Waiting for it to be rectified. Thanks.

**Comment by samvanemelen** [comment]
Alright! The error was a fault in an if-statement when creating the custom meta data for the post. This is fixed and posting should work again. If you also cannot reproduce the error anymore I will close the issue

**Comment by cckole** [comment]
Nice fix. I just posted through it now.  Now working fine.
