### ISSUE TITLE
When i set the upvote slider to 0.01% to upvote a discussion i got an error message.

### ISSUE THREAD

**Issue by darewealth** [samvanemelen/debato#12]
### Describe the bug.
I set my voting slider to 0.01 and upvoted a discussion but I got an error message.
(Could not broadcast vote. Please refresh the page and try again)

### Steps to reproduce.
* Login into debato with your Steem username and key

* Open any discussion and click on the menu icon  

* Set your upvotes to 0.01% and go back to upvote

* You will get an error message. (Could not broadcast vote. Please refresh the page and try again)

### Expected Behaviour
I expected the discussion I upvoted to broadcasted irrespective of any percent set on the voting slider.

### Screen recording
https://youtu.be/_d3T5nUZ29o

### Devices and Versions)
* Device: [Gionee x1]

* Android [7.0]

* Browser: Chrome.

**Comment by cckole** [comment]
I was able to reproduce it both on mobile and PC.

**Comment by samvanemelen** [comment]
Thank you! The issue occurs when you change the vote percentage to any value. The updated percentage would store as a string rather than a number. This caused the upvote function to throw an error. Should be fixed!
