### ISSUE TITLE
Bug: The power up and power down features does not work.

### ISSUE THREAD

**Issue by darewealth** [samvanemelen/debato#14]
### Describe the bug.
I'm unable to power up steem and can't power down. When I input the amount of steem I want to power up and click power up it takes me back to my wallet.

### Steps to reproduce.
* Login into debato with your Steem username and key

* Click on the menu icon and click on 'My profile' 

* Go to the wallet and power up!

### Expected Behaviour
I expected that the power-up and power down works normal.

### Screen recording
https://youtu.be/c7IbsDhaI6U

### Devices and Versions)
* Device: [Gionee x1]

* Android [7.0]

* Browser: Chrome.

**Comment by samvanemelen** [comment]
Thank you for pointing this out. The JavaScript function to create these signing links for steemconnect seems discontinued. Now the signing links will be created by debato itself. Everything should function again.

**Comment by darewealth** [comment]
It works perfectly. :+1:
