### ISSUE TITLE
The feature to transfer funds does not work

### ISSUE THREAD

**Issue by darewealth** [samvanemelen/debato#15]
### Describe the bug.
I'm unable to transfer fund steem/SBD, When I input the amount of steem I want to transfer and click transfer fund it takes me back to my wallet.

### Steps to reproduce.
* Login into debato with your Steem username and key

* Click on the menu icon and click on 'My profile' 

* Go to the wallet and transfer fund!

### Expected Behaviour
I expected that the transfer fund function should work perfectly.

### Screen recording
https://youtu.be/CPKZk-fF3hg

### Devices and Versions)
* Device: [Gionee x1]

* Android [7.0]

* Browser: Chrome.

**Comment by samvanemelen** [comment]
Thank you for pointing this out. Same as the other issue, The JavaScript function to create these signing links for steemconnect seems discontinued. Now the signing links will be created by debato itself. Everything should function again.

**Comment by darewealth** [comment]
It works perfectly.
