### ISSUE TITLE
The voting power percentage never reach 100% on the debato site

### ISSUE THREAD

**Issue by darewealth** [samvanemelen/Debato#17]
### Describe the bug.
I noticed the voting power percentage never reach 100% on the site. I have not voted for long and it shows 100% on other interface but it shows 91.71% on my phone.

### Steps to reproduce.
* Login into debato with your Steem username and key

* Click on the menu icon and click on 'My profile' 

* To see the percentage 

### Expected Behaviour
I expect to see the correct voting power percentage that I have remaining 

### Screenshot.
![Screenshot_20190605-080223](https://user-images.githubusercontent.com/36304257/59133340-9115a200-896f-11e9-9023-659fcbc395e1.png)

### Devices and Versions)
* Device: [Gionee x1]

* Android [7.0]

* Browser: Chrome.

**Comment by samvanemelen** [comment]
Thank you for pointing this out! The voting power attribute of a user's profile returns the voting power at the last upvote. But indeed this is always an outdated value. This is fixed by adding the VP that generated since the time of last upvote.
