### ISSUE TITLE
Add the "Access to User Profile" and "Hot Discussion" Features on Debato

### ISSUE THREAD

**Issue by ahyar92** [samvanemelen/debato#3]
### Components
The components (Features) I want to suggest is:
**1. Access to User Profile**
**2. Hot Discussion**

### Proposal Description
I know Debato from my friends' posts on Steemit. First I saw Debato, I think the developer has a very unique idea. I really appreciated and was impressed with the idea of ​​the Debato developer. I think this is a very good concept.

But after I searched further, Debato had not been actively used by users. There may be several factors that need to be refined by developers to popularize Debato.

In my opinion, in terms of appearance and feature aspects, it needs to be renewed again to make Debato more attractive. In terms of appearance is still simple, and in terms of features are still still fairly lacking. Users need features that allow users to feel at home using Debato. I can understand it, the developer might still need some additional suggestions or ideas from the user so the developer can know what Debato users want. Therefore, I want to suggest some features for Debato which I think the following features can have a good effect.

**Access to User Profile**
At first I tried to browse the Debato platform, and when I opened one of the discussions, and tried to open the profile that opened the discussion. And it turns out I can't access other user's profiles. In my opinion this is very rigid, for me the "Access to User Profile" feature needs to be added so that I can see other discussions opened by the user and also the list of arguments he made.

And also I'm a fan of debate, and I often idolize debate figures who provide interesting arguments. So the feature is very useful to know more about my debate idol later

> NOTE: (After I search for it) Users can open a user profile, by writing a comment first by adding another user's username. Then click the username on the comment. But that is not a good step and certainly confusing. Users need something RESPONSIVE AND FAST, I think direct access is really needed.

**Hot Discussion**
I think the "Hot Discussions" feature is very important to add. But I am surprised, why did the developer not add it. In my opinion, this feature really needs to be added to find out the most hot debates that occurred at that time.

The "Hot Discussion" feature is different from the Trending feature, the Trending Feature will display Debates whose trends are within a long time range. But the "Hot Discussion" feature will display the most Hot Debate that is happening on that day.

#### 1. Access to User Profile
**Original Display,  When I try to open a user profile** **(GIF)**
![doneww.gif](https://cdn.steemitimages.com/DQmdCrjm9q4ob2T7KChGR99fEC8AhjGUBUHshRhCZA78hv9/doneww.gif)

**Example Illustration of the "Access to User Profile" feature that I recommend if applied (Video)**
Https://youtu.be/yy2ocA4oF9U

#### 2. Hot Discussion
**Original Display**
![view.png](https://cdn.steemitimages.com/DQmXkSig5xLoxFvxLT2Wj4n2wdaAVU8zFQc9XX5b73TSn7N/view.png)

**(EXAMPLE) Below, a great location for feature placement "Hot Discussion"**
![gege5.png](https://cdn.steemitimages.com/DQmWiWWR6U6jp24ejA62gH2YD3fWehSRFjnE6JtWeTgh1f5/gege5.png)

![gjgjg.png](https://cdn.steemitimages.com/DQmPQR191gxVmgj4dAEWEP954QaVniRpJRvjBiJUck7vRk5/gjgjg.png)

### Benefits
The benefits of the two features above are as follows:

- As I explained the point above. With the "Access to User Profile" feature, Users can see other user's profiles. So that users who take part in the debate can see the user's profile that opens the discussion to see the other discussion pages of that user.
- With the "Access to User Profile" feature it will certainly give a unique and useful impression. Because it won't make users wonder who opened the discussion. and of course with these feature, we can get to know each other between users by accessing their profiles

- With the "HOT DISCUSSIONS" feature, users can see a list of debates that were hot at that time. This is certainly very interesting, because we can know and join in a very interesting debate, of course.
- This feature will certainly add cool value to Debato, added with the "HOT" icon that will give an interesting impression.

### Conclusion
The above features in my opinion are very necessary to add value to the Debato Platform. And the features that I recommend are only limited to illustrations, I hope the "Debato Developer" can further develop my idea.

**Comment by samvanemelen** [comment]
Thank you for the feedback! In the mean time both features have been implemented. There is now a tab to filter hot topics and a small flame icon is also displayed when a post is hot! Styling of this feature might still change in the future. Now there are not yet any hot posts but at least the framework is present to accommodate it.
