### ISSUE TITLE
Edit debate is set to localhost

### ISSUE THREAD

**Issue by tobias-g1** [samvanemelen/debato#4]
#### Expected Behaviour

A user should be able to edit a debate. 

#### Actual Behaviour

When attempting to edit a debate your directed to localhost. 

#### Recording of Issue

The following shows the issue in more details

![feb-27-2019 18-46-25](https://user-images.githubusercontent.com/17148879/53514859-9a65b780-3ac0-11e9-8013-17018c3628a9.gif)

#### Error

The error can be found here:

https://github.com/samvanemelen/debato/blob/af5205ebab45a39f9932a18ff1f168a5d5c6ac62/js/commons.js#L597

Localhost should be removed to make the URL relative

**Comment by samvanemelen** [comment]
Thank you for pointing it out! It has been resolved [in this commit].(https://github.com/samvanemelen/debato/commit/6e2588bd9eb32a09424cafaf8f5a82c5e18cddbd)
