### ISSUE TITLE
Add Responsive Template For Mobile | Suggestion For Debato

### ISSUE THREAD

**Issue by ahyar92** [samvanemelen/debato#5]
### Components
The components (Features) I want to suggest is: 
***Responsive Template For Mobile***

### Proposal Description
Debato is a project that must be supported. Therefore, I currently want to play a role in giving advice or input to add value to Debato. I am sure, not many people think of establishing projects like Debato. The concept that was presented in my opinion was quite unique, although improvements still needed to be made to make Debato a perfect concept, but that was not a big problem, because Debato was still said to be a new project.

To create a perfect project, I am sure Debato needs several conceptors or contributors to find out what users need in the future. Therefore, I want to be a part to help Debato become a perfect project or platform.  In my opinion, user convenience is the first thing that must be considered by Debato developers. I have tried to explore Debato and I found a problem about the user comfort that Debato needed to respond to. As for the comfort problem I mean the display of Debato which is not responsive for mobile / smartphone.

![tessss.png](https://cdn.steemitimages.com/DQmQBLQsZFDZaFBcrtYXwf8Ls7q83vnKLg3ta7Ef29EvAqK/tessss.png)

**What is a responsive template?**
Responsive templates is  templates design that allow the layout to change depending on the screen resolution when appearing. Cool web design is not only enough for users. Users need responsive web design to get comfort when accessing it. Therefore, debato must make improvements to the design of the web display to support when users access Debato via Mobile.

There are some problems that appear on Debato when the template is unresponsive:
- the user cannot see every detail specifically
- users cannot access the site flexibly
- the user must zoom to access the menu (that is a boring thing for the user)

##### There is a BUG
But there was one more problem that happened, I found a problem (BUG) when I accessed the features in the profile. Display menus such as **Start Discussion, My Profile, and Log out** do not appear.

https://youtu.be/yKvYNaXp5KI

You can see in the video above, I really can't access the features above.

For some of the reasons above, I think the Debato developer will accept my suggestion. In this suggestion, I also want to share one of the template design examples in the mobile version that might be an illustration later for Debato developers.

### Mockups / Examples
Below is an example of the design or layout of the Debato template on the mobile version.
![EEEE.png](https://cdn.steemitimages.com/DQmdFKZJiFQG9N3hjf6REvrEbWAaZKec5X1Z9pakESPGbK5/EEEE.png)
![dadadw.png](https://cdn.steemitimages.com/DQmXtqtMhYFtZP8nKsGJv3JS23jBTn6xcTR7Zp3BU5Mic4C/dadadw.png)

![#2.png](https://cdn.steemitimages.com/DQmbimpFAbo4CPf4Huc3DKAGtK8ScxqbWtkvhbPTY6EJWsA/#2.png)
![#22.png](https://cdn.steemitimages.com/DQmbRb5Nmvi9FYcmC9kF1UW6Q41BDK2GE9GJ56xdGxEWZpd/#22.png)

![#3.png](https://cdn.steemitimages.com/DQmPqY36JyNT5tySMp7yXTyyLQWeoikaDfGbbeD6rvNh2WY/#3.png)
![#33.png](https://cdn.steemitimages.com/DQmWS2pTrb65UCUaZcZGjhFfNwVT3M7EWwoTrqDCW66eBmx/#33.png)

![#4.png](https://cdn.steemitimages.com/DQmdmnec8GRdSnLLhtbjfzALMRAVuNqJWXubkNLAAYkxWhm/#4.png)
![#444.png](https://cdn.steemitimages.com/DQmXMsunBuuzm8kFtLP6xFmch31qdWW2RkCi1aR4tqcEbNg/#444.png)

![#5.png](https://cdn.steemitimages.com/DQmZcpQRBCFFLbzfsAT5rRcDvATxtvpzhv9wEKk35eQACZf/#5.png)
![#55.png](https://cdn.steemitimages.com/DQmYsknfabEjV5ftAYUT5ZfCeHRs9fJ2GQB75im7ueLfBtJ/#55.png)

### Benefits
- With the design of a responsive template, the Debato display will adjust according to the screen resolution of the device. This will certainly provide comfort for users, because users can access Debato flexibly and easily.
- With a responsive display, Debato will provide a better user experience and will certainly improve the usability of the Debato platform.
- By providing comfort for users with the appearance of responsive templates, it will certainly increase visitors and make Debato popular.  In addition, half of the world's web traffic comes from mobile devices. That way, the choice to change the appearance of being responsive on Mobile is a good thing. And by providing comfort in a mobile display, of course users will feel at home for long.
- And finally, the responsive template will certainly make Debato in a better SEO rating.

**Comment by samvanemelen** [comment]
Thank you for the suggestion! The responsive version of the site now also accommodates really small screens (mobile) and touch screens (stopped relying on :hover) for each of the pages. 

![](https://user-images.githubusercontent.com/36103001/53682077-5bb74380-3cf2-11e9-8ce4-b1e447b7ff37.png)
![](https://user-images.githubusercontent.com/36103001/53682086-6f62aa00-3cf2-11e9-9cdd-1f3b60edf9ca.png)
