### ISSUE TITLE
Unable to claim rewards. 

### ISSUE THREAD

**Issue by HarryHeights** [samvanemelen/debato#7]
#### Expected Behavior 
I expected that since the function to claim reward is available on the app, I will be able to claim my post rewards.

#### Actual Behavior
I'm unable to claim post rewards. The process is stuck on a never-ending loop. 

#### How to reproduce.
To reproduce this issue, it means one of your posts has paid out and the rewards are avaialble to be claimed. If that prerequisite is available;

- Goto to the [Debato.org](https://debato.org)
- Login
- Goto your profile
- Goto wallet
- Click on claim reward
- See error

#### Test environment
- Brave browser.

#### Screen recording
https://youtu.be/l3moy_OS10o

**Comment by samvanemelen** [comment]
Thank you for pointing this out! Does dis error still persist in your browser? I believe this error was fixed about a week ago.

**Comment by HarryHeights** [comment]
I just checked it out now. The issue has been fixed.
